version: "3.4"
services:
  bonus-register:
    image: node:alpine
    container_name: bonus-register
    entrypoint: /bin/sh
    ports:
      - 9054:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./vue-app
        target: /srv/app
    tty: true
